# C++
[[language]]
name = "cpp"
language-servers = ["clangd"]
auto-format = true

# C
[[language]]
name = "c"
language-servers = ["clangd"]
auto-format = true

[[language]]
name = "rust"
auto-format = true

[[language]]
name = "python"
auto-format = true

[[language]]
name = "bash"
auto-format = true

[[language]]
name = "json"
auto-format = true

[[language]]
name = "nix"
auto-format = true
