[colors]
background = '#131315'
foreground = '#e4e2e5'

cursor_bg = '#b6c7ea'
cursor_fg = '#131315'
cursor_border = '#b6c7ea'

selection_bg = '#344562'
selection_fg = '#e4e2e5'

ansi = ['#131315', '#ff7299', '#75ea86', '#fff872', '#a3b6de', '#404e6c', '#b6c7ea', '#e6ebf5']
brights = ['#8c9098', '#ff9fba', '#a5ffb3', '#fffaa5', '#cedeff', '#d7e4ff', '#e5edff', '#f8faff']
